---
title: "Project Description"
---

After the emergence of COVID-19 in early 2020, undoubtedly many businesses were forced to close temporarily or permanently. Throughout this time, restaurants in particular have undergone various modifications, such as disabling dine-in, starting takeout, etc. As a result, the food quality, service quality, and overall dining experience might have changed - whether in a positive or negative way. 

With that in mind, I propose the research question: How has COVID-19 affected restaurant performance and impression? Specifically, do restaurants with services that better comply with COVID restrictions necessarily have better reviews?

In order to answer this question, I utilized data from Yelp, one of the biggest platforms that displays information of businesses and enable users to search for, react to, and/or share their opinions of such businesses. Their data come from a total of 6,990,280 reviews and 150,346 businesses from 11 metropolitan areas - Montreal, Calgary, Toronto, Pittsburgh, Charlotte, Urbana-Champaign, Phoenix, Las Vegas, Madison, and Cleveland. Only reviews that are [recommended](https://www.yelp-support.com/Recommended_Reviews) by Yelp are included. For privacy reasons, contents of the dataset will not be disclosed.



